### PR TITLE
PHPCS-11: Empty line after declare-statement

### PR DESCRIPTION
**Pull request by bestit-lubisch**

### CODE REVIEW

**Comment by bestit-tkellner** [comment]
Please add an Tests for files which contains more than one declare statement.

**Comment by bestit-lubisch** [comment]
done.

**Comment by bestit-tkellner** [comment]
If i see it right there's still a small "problem". More than one declare control structure must not be separated by new lines.

Correct:
```
<?php

declare();
declare();
declare();

namespace Test;

class Test
{
}
```
Incorrect:
```
<?php

declare();

declare();

declare();

namespace Test;

class Test
{
}
```

**Comment by bestit-lubisch** [comment]
I would prefer that we restrict this sniff only to declare(strict_types=1) because there is also a way to write a declare-block and this would produce a much complicated sniff.

Example:
```php
<?php
function handler(){
    print "hello <br />";
}

register_tick_function("handler");

declare(ticks = 1){
    $b = 2;
}
```

**Comment by bestit-tkellner** [comment]
Nope. Sorry.

The requirements in PHPCS-11 are for all declare statements.

**Comment by bestit-tkellner** [comment]
Requirements changed.

**Pull request merged**
